Initial implementation of the primary rating calculator
osu-tournament-rating/otr-processor pull request #35
Opened 2024-03-13 13:19 UTC by Chiffario

This is a first pass on #6.

`calc_ratings()` calculates ratings and ranks based on the given set of matches. The goal of this PR specifically is to get at least a "placeholder" calculator to optimize/rewrite later on, and also to get both @hburn7 and @486c to check the logic correctness, as there are a LOT of moving parts here

2024-03-13 15:05 UTC, hburn7 requested changes
Mainly documentation requests, but I did find a couple of issues (at least in my own tests). Overall, I don't see any flawed logic.

2024-03-13 15:05 UTC, hburn7 commented on src/model/mod.rs
> +                    // We subtract 1.0 here because
Clarify the 1.0 subtraction is for player 1

2024-03-13 15:05 UTC, hburn7 commented on src/model/mod.rs
> +                    mu: 1500.0,
This needs to be 1499.0

2024-03-13 15:05 UTC, hburn7 commented on src/model/mod.rs
> +        // TODO: Figure out why the differences are this large
Probably because of L753

2024-03-13 15:05 UTC, hburn7 commented on src/model/mod.rs
> +            (loser_expected_outcome.mu - loser_stats.rating_after).abs() < 1.0,
Definitely use epsilon instead of 1.0, the outcomes should be exactly equal.

2024-03-14 13:58 UTC, hburn7 commented on src/model/mod.rs
> +                    mu: 1500.0,
Fixed

2024-03-15 06:28 UTC, S1n1st3rn3ss commented on src/model/mod.rs
> +
Counter-argument: a TeamVS match with a head-to-head Tiebreaker "showmatch", I think it should still be based on counts with an exception for when those are equal, not *just* when both are > 0

2024-03-15 06:31 UTC, S1n1st3rn3ss commented on src/model/mod.rs
> +                let mut curr_player_team = 1;
that check in general is incorrect and I have no idea how I let it through, will fix

2024-03-15 06:35 UTC, S1n1st3rn3ss commented on src/model/mod.rs
> +                let mut curr_player_team = 1;
I'd prefer creating an enum for team colors later down the line but a constant should work for now

2024-03-15 06:40 UTC, S1n1st3rn3ss commented on src/model/mod.rs
> +        let model_rating = model.rate(teams, ranks);
as I clarified in the Discord, ranks are "the lower the better" in the model, but match costs are the opposite, so reversing the order is required for the accurate pairing

2024-03-16 08:52 UTC, 486c commented
You save multiple allocations here:
```rust
pub fn create_initial_ratings(matches: &Vec<Match>, players: &Vec<Player>) -> Vec<PlayerRating> {
    ...
    ...
    // Map the osu ids for fast lookup
    let mut player_hashmap: HashMap<i32, Player> = HashMap::new();
```

by changing 
```rust
let mut player_hashmap: HashMap<i32, Player> = HashMap::new();
```
to
```rust
let mut player_hashmap: HashMap<i32, Player> = HashMap::with_capacity(players.len());
```

2024-03-16 08:55 UTC, 486c commented
same here
```rust
pub fn hash_country_mappings(country_mappings: &Vec<PlayerCountryMapping>) -> HashMap<i32, Option<String>> {
    let mut country_mappings_hash: HashMap<i32, Option<String>> = HashMap::new();

    for c in country_mappings {
        country_mappings_hash.insert(c.playerId, c.country.clone());
    }

    country_mappings_hash
}
```

```
let mut country_mappings_hash: HashMap<i32, Option<String>> = HashMap::with_capacity(country_mappings.len());
```

Also take slices instead of whole vector ;)
`&Vec<PlayerCountryMapping>` to `&[PlayerCountryMapping]`

2024-04-27 15:25 UTC, merged